extern crate cbindgen;

use std::env;
use cbindgen::DocumentationStyle;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    //let target_dir = match env::var("CARGO_TARGET_DIR") {
    //    Ok(target) => target,
    //    Err(_error) => String::from("target")
    //};
    //let header_file = format!("{}/include/rust_lib.h", target_dir);
    let header_file = format!("{}/include/rust_lib/rust_lib.h", crate_dir);

    let mut config: cbindgen::Config = Default::default();
    config.language = cbindgen::Language::C;
    config.include_guard = Some(String::from("RUST_LIB_H_INCLUDED"));
    config.no_includes = true;
    config.sys_includes.push(String::from("stdint.h"));
    config.cpp_compat = true;
    //config.autogen_warning = Some(String::from("This file is automatically generated. Do not edit."));
    config.documentation = true;
    config.documentation_style = DocumentationStyle::Doxy;
    cbindgen::generate_with_config(&crate_dir, config)
      .unwrap()
      .write_to_file(header_file);

    // documentation style not supported in builder yet
    /*
    cbindgen::Builder::new()
      .with_crate(crate_dir)
      .with_language(cbindgen::Language::C)
      .with_include_guard("RUST_LIB_H_INCLUDED")
      .with_no_includes()
      .with_sys_include("stdint.h")
      .with_cpp_compat(true)
      //.with_autogen_warning("This file is automatically generated. Do not edit.")
      .with_documentation(true)
      //.with_documentation_style(DocumentationStyle::Doxy)
      .generate()
      .expect("Unable to generate bindings")
      .write_to_file(header_file);
    */
}
